function createaxes1(Parent1, X1, Y1, X2, Y2)
%CREATEAXES1(Parent1, X1, Y1, X2, Y2)
%  PARENT1:  axes parent
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 13-Oct-2020 13:40:08

% Create axes
axes1 = axes('Parent',Parent1);
hold(axes1,'on');
colororder([0.85 0.325 0.098]);

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create plot
plot(X1,Y1,'DisplayName','TGT-ABW-TGT (Transmitance)',...
    'MarkerFaceColor',[0 0 1],...
    'MarkerSize',10,...
    'Marker','hexagram',...
    'LineWidth',1,...
    'LineStyle','--',...
    'Color',[1 0.074509803921569 0.650980392156863]);

% Create plot
plot(X2,Y2,'DisplayName','TCT-ABW-TCT (Transmitance)',...
    'MarkerFaceColor',[0 0 1],...
    'MarkerSize',10,...
    'Marker','square',...
    'LineWidth',1,...
    'Color',[0 0 1]);

% Create ylabel
ylabel('Percentage increase in Transmitance Performance');
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[20 55]);

% Set the remaining axes properties
set(axes1,'YColor',[0 0 0],'YDir','normal','YMinorTick','off');
% Activate the right side of the axes

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[20 55]);

% Set the remaining axes properties
set(axes1,'YColor',[0 0 0]);
% Create xlabel
xlabel('Percentage increase in Structural Performance');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ContextMenu','FontSize',14,'XColor',[0 0 0],'ZColor',[0 0 0]);
